
# SEO settings
title: "thassiov"
title2: "()" # default: ""
description: "O site pessoal de um desenvolvedor backend"
keywords: "backend, developer, desenvolvedor, programador, programmer, software"
url: http://thassiov.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
#repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "heiswayi"
#twitter_username: "HeiswayiNrird"
#comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Thassio Victor"
  job      : "Desenvolvedor Backend"
  bio      : "Quando não estou desenvolvendo algum programa, estou escrevendo 
    para o meu blog ou fuçando fóruns de astronomia."
  thumb    : /images/author.jpg
  #email    : 
  url      : http://thassiov.github.io
  github   : http://github.com/thassiov
  #twitter  : 
  #facebook : 
  linkedin : http://br.linkedin.com/in/thassiov

# social settings
#og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
